{% set scip_version = "7.0.2" %}
{% set soplex_version = "5.0.2" %}
{% set gcg_version = "3.0.4" %}
{% set zimpl_version = "3.4.0" %}
{% set bliss_version = "0.73.3" %}

package:
  name: scipoptsuite
  version: {{ scip_version }}

source:
  - url: https://scip.zib.de/download/release/scipoptsuite-{{ scip_version }}.tgz
    sha256: f81b5a2c1c0eb949cf06bd50f42826e55284fa1269a6f28a92ac1a06d9c93a03
    folder: scipoptsuite
  - url: https://github.com/ds4dm/Bliss/archive/v{{ bliss_version }}.tar.gz
    sha256: 4f51d9f76f7e8cb941688a032d208c79858f68a95f8eb69ebef64c62932c3eb7
    folder: bliss

build:
  number: 6

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make            # [unix]
  host:
    - tbb-devel
    - libblas
    - zlib
    - ipopt
    - cppad
    - boost-cpp 1.72  # [win]
    - boost-cpp       # [unix]
    - gmp             # [unix]
    - cliquer         # [unix]
    - bison           # [unix]
    - flex            # [unix]

outputs:

  - name: scip
    version: {{ scip_version }}
    build:
      run_exports:
        - {{ pin_subpackage('scip') }}
    requirements:
      build:
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - tbb-devel
        - libblas
        - zlib
        - ipopt
        - cppad
        - gmp  # [unix]
    files:
      - "lib/libscip*"                    # [unix]
      - "lib/cmake/scip/"                 # [unix]
      - "include/blockmemshell/"          # [unix]
      - "include/dijkstra/"               # [unix]
      - "include/lpi/"                    # [unix]
      - "include/nlpi/"                   # [unix]
      - "include/objscip/"                # [unix]
      - "include/scip/"                   # [unix]
      - "include/symmetry/"               # [unix]
      - "include/tclique/"                # [unix]
      - "include/tinycthread/"            # [unix]
      - "include/tpi/"                    # [unix]
      - "include/xml/"                    # [unix]
      - "bin/scip"                        # [unix]
      - "Library/lib/libscip.lib"         # [win]
      - "Library/bin/libscip.dll"         # [win]
      - "Library/lib/cmake/scip/"         # [win]
      - "Library/include/blockmemshell/"  # [win]
      - "Library/include/dijkstra/"       # [win]
      - "Library/include/lpi/"            # [win]
      - "Library/include/nlpi/"           # [win]
      - "Library/include/objscip/"        # [win]
      - "Library/include/scip/"           # [win]
      - "Library/include/symmetry/"       # [win]
      - "Library/include/tclique/"        # [win]
      - "Library/include/tinycthread/"    # [win]
      - "Library/include/tpi/"            # [win]
      - "Library/include/xml/"            # [win]
      - "Library/bin/scip.exe"            # [win]

    test:
      script: run_scip_test.sh   # [unix]
      script: run_scip_test.bat  # [win]
      source_files:
        - scipoptsuite/scip/examples/Queens
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - make                   # [unix]

  - name: soplex
    version: {{ soplex_version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - zlib
        - gmp             # [unix]
        - boost-cpp       # [unix]
        - boost-cpp 1.72  # [win]
      run:
        # libboost_program_options.so needed by bin/soplex.
        # boost does not set run_exports so it is needed in run requirements.
        - boost-cpp
    files:
      - "lib/libsoplex*"              # [unix]
      - "lib/cmake/soplex/"           # [unix]
      - "include/soplex*"             # [unix]
      - "include/soplex/"             # [unix]
      - "bin/soplex"                  # [unix]
      - "Library/lib/soplex.lib"      # [win]
      - "Library/lib/soplex-pic.lib"  # [win]
      - "Library/lib/cmake/soplex/"   # [win]
      - "Library/include/soplex*"     # [win]
      - "Library/include/soplex/"     # [win]
    test:
      script: run_soplex_test.sh   # [unix]
      script: run_soplex_test.bat  # [win]
      source_files:
        - scipoptsuite/soplex/src/example.cpp
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - make                     # [unix]

  - name: gcg
    version:  {{ gcg_version }}
    build:
      skip: True  # [win]
      run_exports:
        - {{ pin_subpackage('gcg') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - gmp
        - cliquer
        - {{ pin_subpackage('scip', exact=True) }}
      run:
        - {{ pin_subpackage('scip') }}
        # run_exports not set for cliquer
        - cliquer
    files:
      - "lib/libgcg*"
      - "lib/cmake/gcg"
      - "include/gcg"
      - "bin/gcg"
    test:
      commands:
        - gcg --version
        - test -d "${PREFIX}/lib/cmake/gcg"
        - test -d "${PREFIX}/include/gcg"

  - name: zimpl
    version: {{ zimpl_version }}
    build:
      # zimpl is not built in Windows since gmp is not available on 
      # conda-forge so this test is skipped. Details were left for 
      # the path to zimpl if we find a solution in the future.  
      skip: True  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - zlib
        - gmp    # [unix]
        - bison  # [unix]
        - flex   # [unix]
    files:
      - "lib/libzimpl*"             # [unix]
      - "lib/cmake/zimpl/"          # [unix]
      - "include/zimpl"             # [unix]
      - "bin/zimpl"                 # [unix]
      - "Library/lib/libzimpl*"     # [win]
      - "Library/lib/cmake/zimpl/"  # [win]
      - "Library/include/zimpl"     # [win]
      - "Library/bin/zimpl.exe"     # [win]
    test:
      commands:
        - zimpl -V
        - test -d "${PREFIX}/lib/cmake/zimpl"                                   # [unix]
        - test -d "${PREFIX}/include/zimpl"                                     # [unix]
        - if exist %PREFIX%\\Library\\lib\\cmake\\zimpl (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\\Library\\include\\zimpl (exit 0) else (exit 1)     # [win]


about:
  home: https://scipopt.org/
  license: ZIB-Academic AND LGPL-3.0-or-later
  license_file:
    - scipoptsuite/COPYING
    - bliss/COPYING.LESSER
    - bliss/include/bliss/utils.hh
  summary: Mixed Integer Programming (MIP) solver and Branch-and-Cut-and-Price Framework

extra:
  recipe-maintainers:
    - AntoinePrv
    - pokutta
    - fschloesser
