# TODO check these versions have not changed
{% set scip_version = "9.0.0" %}
{% set papilo_version = "2.2.0" %}
{% set soplex_version = "8.0.0" %}
{% set gcg_version = "3.6.0" %}
{% set zimpl_version = "3.5.4" %}
# For dispatching between Unix and Windows
{% set install_prefix = "." %}        # [unix]
{% set install_prefix = "Library" %}  # [win]


package:
  name: scipoptsuite
  version: {{ scip_version }}

source:
  - url: https://scipopt.org/download/release/scipoptsuite-{{ scip_version }}.tgz
    sha256: c49a0575003322fcbfe2d3765de7e3e60ff7c08d1e8b17d35409be40476cb98a
    folder: scipoptsuite
    patches:
      - 0002-Require-PCRE-on-WIN32.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - ninja
    - bison           # [unix]
    - flex            # [unix]
    - winflexbison    # [win]
  host:
    - tbb-devel
    - libblas
    - zlib
    - ipopt
    - cppad
    # upstream code not compatible with newer boost, apparently
    - boost-cpp 1.72  # [win]
    - libboost-devel  # [unix]
    - mpfr
    - gmp             # [unix]
    - cliquer         # [unix]
    - pcre2           # [win]

outputs:

  - name: papilo
    version: {{ papilo_version }}
    requirements:
      build:
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - zlib
        - gmp             # [unix]
        - mpfr
        - libboost-headers
        - libblas
      run:
        - tbb-devel
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET | default("10.9") }}  # [osx and x86_64]
    files:
      - "{{ install_prefix }}/lib/cmake/papilo/"
      # Executable is not installed by Papilo's CMake
      # - "{{ install_prefix }}/bin/papilo*"
      # Vendored libraries
      - "{{ install_prefix }}/lib/libclusol*"
      - "{{ install_prefix }}/lib/libpapilo-core*"
      - "{{ install_prefix }}/include/papilo/"

  - name: scip
    version: {{ scip_version }}
    build:
      run_exports:
        - {{ pin_subpackage('scip') }}
    requirements:
      build:
        - {{ compiler('c') }}
        # Soplex statically linked
        - {{ compiler('cxx') }}
        # Papilo statically linked but needs direct dependency from used shared libs.
        - {{ compiler('fortran') }}
      host:
        - zlib
        - ipopt
        - cppad
        - gmp   # [unix]
        - mpfr
        # Papilo statically linked
        # Papilo statically linked but needs direct dependency from used shared libs.
        - tbb-devel
        - libblas
        # zimpl statically linked, transitive usage requirements
        - pcre2  # [win]
    files:
      - "{{ install_prefix }}/lib/libscip*"
      - "{{ install_prefix }}/lib/cmake/scip/"
      - "{{ install_prefix }}/bin/scip*"
      - "{{ install_prefix }}/bin/libscip*"  # [win]
      - "{{ install_prefix }}/include/blockmemshell/"
      - "{{ install_prefix }}/include/dijkstra/"
      - "{{ install_prefix }}/include/lpi/"
      - "{{ install_prefix }}/include/nlpi/"
      - "{{ install_prefix }}/include/objscip/"
      - "{{ install_prefix }}/include/scip/"
      - "{{ install_prefix }}/include/symmetry/"
      - "{{ install_prefix }}/include/tclique/"
      - "{{ install_prefix }}/include/tinycthread/"
      - "{{ install_prefix }}/include/tpi/"
      - "{{ install_prefix }}/include/xml/"

    test:
      script: run_scip_test.sh   # [unix]
      script: run_scip_test.bat  # [win]
      source_files:
        - scipoptsuite/scip/examples/Queens
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - ninja

  - name: soplex
    version: {{ soplex_version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        # Papilo statically linked but needs direct dependency from used shared libs.
        - {{ compiler('fortran') }}
      host:
        - zlib
        - gmp             # [unix]
        - mpfr
        - boost-cpp 1.72  # [win]
        - libboost-devel  # [unix]
        # Papilo statically linked but needs direct dependency from used shared libs.
        - tbb-devel
        - libblas
      run:
        # old boost-cpp does not set run_exports, need to set it manually
        - boost-cpp 1.72  # [win]
        - zlib
        - {{ pin_subpackage('papilo', exact=True) }}
    files:
      - "{{ install_prefix }}/lib/libsoplex*"
      - "{{ install_prefix }}/lib/cmake/soplex/"
      - "{{ install_prefix }}/bin/soplex*"
      - "{{ install_prefix }}/bin/libsoplex*"  # [win]
      - "{{ install_prefix }}/include/soplex*"
      - "{{ install_prefix }}/include/soplex/"
    test:
      script: run_soplex_test.sh   # [unix]
      script: run_soplex_test.bat  # [win]
      source_files:
        - scipoptsuite/soplex/src/example.cpp
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - ninja
        # Papilo statically linked
        - {{ compiler('fortran') }}
        # compiling the example needs to find boost metadata
        - libboost-devel  # [unix]

  - name: gcg
    version:  {{ gcg_version }}
    build:
      skip: True  # [win]
      run_exports:
        - {{ pin_subpackage('gcg') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - gmp
        - cliquer
        - gnuplot
        - {{ pin_subpackage('scip', exact=True) }}
      run:
        - {{ pin_subpackage('scip') }}
        # run_exports not set for cliquer
        - cliquer
    files:
      - "lib/libgcg*"
      - "lib/cmake/gcg"
      - "bin/gcg"
      - "include/gcg"
    test:
      commands:
        - gcg --version
        - test -d "${PREFIX}/lib/cmake/gcg"
        - test -d "${PREFIX}/include/gcg"

  - name: zimpl
    version: {{ zimpl_version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - bison  # [unix]
        - flex   # [unix]
        - winflexbison  # [win]
      host:
        - zlib
        - gmp    # [unix]
        - mpfr
        - pcre2  # [win]
    files:
      - "{{ install_prefix }}/lib/libzimpl*"  # [unix]
      - "{{ install_prefix }}/lib/zimpl*"     # [win]
      - "{{ install_prefix }}/lib/cmake/zimpl/"
      - "{{ install_prefix }}/bin/zimpl*"
      - "{{ install_prefix }}/include/zimpl"
    test:
      commands:
        - zimpl -V
        - test -d "${PREFIX}/lib/cmake/zimpl"                                   # [unix]
        - test -d "${PREFIX}/include/zimpl"                                     # [unix]
        - if exist %PREFIX%\\Library\\lib\\cmake\\zimpl (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\\Library\\include\\zimpl (exit 0) else (exit 1)     # [win]


about:
  home: https://scipopt.org/
  license: Apache 2.0 AND ZIB-Academic AND LGPL-3.0-or-later
  license_file:
    - scipoptsuite/papilo/COPYING
    - scipoptsuite/papilo/src/papilo/external/lusol/LICENSE.md
    - scipoptsuite/papilo/src/papilo/external/pdqsort/license.txt
    - scipoptsuite/papilo/src/papilo/external/ska/LICENSE.txt
    - scipoptsuite/soplex/LICENSE
    - scipoptsuite/scip/LICENSE
    - scipoptsuite/gcg/LICENSE
    - scipoptsuite/zimpl/LICENSE
  summary: Mixed Integer Programming (MIP) solver and Branch-and-Cut-and-Price Framework

extra:
  recipe-maintainers:
    - ju-manns
    - AntoinePrv
    - pokutta
    - fschloesser
