# TODO check these versions have not changed
{% set scip_version = "10.0.0" %}
{% set papilo_version = "3.0.0" %}
{% set soplex_version = "8.0.0" %}
{% set gcg_version = "4.0.0" %}
{% set zimpl_version = "3.7.0" %}
# For dispatching between Unix and Windows
{% set install_prefix = "." %}        # [unix]
{% set install_prefix = "Library" %}  # [win]


package:
  name: scipoptsuite
  version: {{ scip_version }}

source:
  - url: https://scipopt.org/download/release/scipoptsuite-{{ scip_version }}.tgz
    sha256: 60632b89935c0fd8f5d244dcc25f36504a82b1f68eb847f6e5c0c2c5d5936f39
    folder: scipoptsuite
    patches:
      # header-only does not work with current boost due to https://github.com/boostorg/serialization/issues/232
      - 0001-disable-boost-no-lib.patch  # [win]
      # conda-forge::jansson for windows contains only a static debug lib of jansson; make gcg use this one
      - 0002-allow-jansson-debug-lib.patch  # [win]

build:
  number: 1

# to reduce disk space use on Windows, I disabled the Fortran compiler there (https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=windows-images%2Cyaml#my-pipeline-fails-with-the-error-no-space-left-on-device)
# this disables LUSOL for Papilo, and then libblas is no longer needed as well

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - ninja
    - bison           # [unix]
    - flex            # [unix]
    - winflexbison    # [win]
  host:
    - tbb-devel
    - libblas         # [unix]
    - zlib
    - ipopt
    - libboost-devel
    - mpfr
    - gmp
    - cliquer         # [unix]
    - pcre2           # [win]
    - jansson
    - highs

outputs:

  - name: papilo
    version: {{ papilo_version }}
    requirements:
      build:
        - {{ compiler('fortran') }}  # [unix]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - zlib
        - gmp
        - mpfr
        - highs
        # to run the papilo exe, boost libs are needed on unix as well
        - libboost-devel
        - libblas  # [unix]
      run:
        - tbb-devel
        # papilo executable depends on scip library
        - {{ pin_subpackage('scip') }}
        - highs
    files:
      - "{{ install_prefix }}/lib/cmake/papilo/"
      - "{{ install_prefix }}/bin/papilo*"
      - "{{ install_prefix }}/include/papilo/"
      # Vendored libraries
      - "{{ install_prefix }}/lib/libclusol*"
      - "{{ install_prefix }}/lib/libpapilo-core*"
    test:
      commands:
        - papilo
        - test -d "${PREFIX}/lib/cmake/papilo"  # [unix]
        - test -d "${PREFIX}/include/papilo"    # [unix]
        - if exist %PREFIX%\\Library\\lib\\cmake\\papilo (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\\Library\\include\\papilo (exit 0) else (exit 1)     # [win]

  - name: scip
    version: {{ scip_version }}
    build:
      run_exports:
        - {{ pin_subpackage('scip') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        # Soplex statically linked
        - {{ compiler('cxx') }}
        # Papilo statically linked but needs direct dependency from used shared libs.
        - {{ compiler('fortran') }}  # [unix]
      host:
        - zlib
        - ipopt
        - gmp
        - mpfr
        # Papilo statically linked
        # Papilo statically linked but needs direct dependency from used shared libs.
        - tbb-devel
        - libblas  # [unix]
        # zimpl statically linked, transitive usage requirements
        - pcre2  # [win]
        - libboost-devel  # [win]
    files:
      - "{{ install_prefix }}/lib/libscip*"
      - "{{ install_prefix }}/lib/cmake/scip/"
      - "{{ install_prefix }}/bin/scip*"
      - "{{ install_prefix }}/bin/libscip*"  # [win]
      - "{{ install_prefix }}/include/blockmemshell/"
      - "{{ install_prefix }}/include/dijkstra/"
      - "{{ install_prefix }}/include/lpi/"
      - "{{ install_prefix }}/include/lpiexact/"
      - "{{ install_prefix }}/include/objscip/"
      - "{{ install_prefix }}/include/scip/"
      - "{{ install_prefix }}/include/symmetry/"
      - "{{ install_prefix }}/include/tclique/"
      - "{{ install_prefix }}/include/tinycthread/"
      - "{{ install_prefix }}/include/tpi/"
      - "{{ install_prefix }}/include/xml/"

    test:
      script: run_scip_test.sh   # [unix]
      script: run_scip_test.bat  # [win]
      source_files:
        - scipoptsuite/scip/examples/Queens
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - ninja

  - name: soplex
    version: {{ soplex_version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        # Papilo statically linked but needs direct dependency from used shared libs.
        - {{ compiler('fortran') }}  # [unix]
        - {{ stdlib("c") }}
      host:
        - zlib
        - gmp
        - mpfr
        - libboost-headers  # [unix]
        - libboost-devel    # [win]
        # Papilo statically linked but needs direct dependency from used shared libs.
        - tbb-devel
        - libblas  # [unix]
      run:
        - zlib
        - {{ pin_subpackage('papilo', exact=True) }}
    files:
      - "{{ install_prefix }}/lib/libsoplex*"
      - "{{ install_prefix }}/lib/cmake/soplex/"
      - "{{ install_prefix }}/bin/soplex*"
      - "{{ install_prefix }}/bin/libsoplex*"  # [win]
      - "{{ install_prefix }}/include/soplex*"
      - "{{ install_prefix }}/include/soplex/"
    test:
      script: run_soplex_test.sh   # [unix]
      script: run_soplex_test.bat  # [win]
      source_files:
        - scipoptsuite/soplex/src/example.cpp
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - ninja
        # Papilo statically linked
        - {{ compiler('fortran') }}  # [unix]
        # compiling the example needs to find boost
        - libboost-devel

  - name: gcg
    version:  {{ gcg_version }}
    build:
      run_exports:
        - {{ pin_subpackage('gcg') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - gmp
        - cliquer   # [unix]
        - gnuplot   # [unix]
        - {{ pin_subpackage('scip', exact=True) }}
        - libboost-devel  # [win]
        - jansson
        - highs
      run:
        - {{ pin_subpackage('scip') }}
        # run_exports not set for cliquer
        - cliquer   # [unix]
        - highs
    files:
      - "{{ install_prefix }}/lib/libgcg*"
      - "{{ install_prefix }}/lib/cmake/gcg"
      - "{{ install_prefix }}/bin/gcg*"
      - "{{ install_prefix }}/bin/libgcg*"  # [win]
      - "{{ install_prefix }}/include/gcg"
      - "{{ install_prefix }}/include/graph"
    test:
      commands:
        - gcg --version
        - test -d "${PREFIX}/lib/cmake/gcg"  # [unix]
        - test -d "${PREFIX}/include/gcg"    # [unix]
        - test -d "${PREFIX}/include/graph"  # [unix]
        - if exist %PREFIX%\\Library\\lib\\cmake\\gcg (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\\Library\\include\\gcg (exit 0) else (exit 1)     # [win]
        - if exist %PREFIX%\\Library\\include\\graph (exit 0) else (exit 1)   # [win]

  - name: zimpl
    version: {{ zimpl_version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - bison  # [unix]
        - flex   # [unix]
        - winflexbison  # [win]
      host:
        - zlib
        - gmp
        - mpfr
        - pcre2  # [win]
    files:
      - "{{ install_prefix }}/lib/libzimpl*"  # [unix]
      - "{{ install_prefix }}/lib/zimpl*"     # [win]
      - "{{ install_prefix }}/lib/cmake/zimpl/"
      - "{{ install_prefix }}/bin/zimpl*"
      - "{{ install_prefix }}/include/zimpl"
    test:
      commands:
        - zimpl -V
        - test -d "${PREFIX}/lib/cmake/zimpl"                                   # [unix]
        - test -d "${PREFIX}/include/zimpl"                                     # [unix]
        - if exist %PREFIX%\\Library\\lib\\cmake\\zimpl (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\\Library\\include\\zimpl (exit 0) else (exit 1)     # [win]


about:
  home: https://scipopt.org/
  license: Apache-2.0 AND LGPL-3.0-or-later AND EPL-1.0 and MIT and Zlib and BSL-1.0 and HPND
  license_file:
    - scipoptsuite/papilo/LICENSE  # Apache 2.0
    - scipoptsuite/papilo/src/papilo/external/lusol/LICENSE.md  # BSD or MIT
    - scipoptsuite/papilo/src/papilo/external/pdqsort/license.txt  # Zlib
    - scipoptsuite/papilo/src/papilo/external/ska/LICENSE.txt # Boost 1.0 (BSL-1.0)
    - scipoptsuite/papilo/src/papilo/external/fmt/LICENSE.rst  # MIT
    - scipoptsuite/soplex/LICENSE  # Apache 2.0
    - scipoptsuite/soplex/src/soplex/external/zstr/License.txt  # MIT
    - scipoptsuite/soplex/src/soplex/external/fmt/LICENSE.rst  # MIT
    - scipoptsuite/scip/LICENSE  # Apache 2.0
    - scipoptsuite/scip/src/amplmp/LICENSE.rst  # HPND, similar to ISC
    - scipoptsuite/scip/src/cppad/COPYING  # EPL-1.0
    - scipoptsuite/scip/src/dejavu/LICENSE  # MIT
    - scipoptsuite/scip/src/nauty/COPYRIGHT  # Apache 2.0
    - scipoptsuite/scip/src/tclique/LICENSE  # Apache 2.0
    - scipoptsuite/scip/src/tinycthread/COPYRIGHT  # Zlib
    - scipoptsuite/gcg/LICENSE  # Apache 2.0
    - scipoptsuite/zimpl/LICENSE  # LGPL 3
  summary: Constraint Integer Programming and Branch-and-Cut-and-Price Framework

extra:
  recipe-maintainers:
    - AntoinePrv
    - scip-ci
