# TODO check these versions have not changed
{% set scip_version = "8.0.0" %}
{% set papilo_version = "2.0.0" %}
{% set soplex_version = "6.0.0" %}
{% set gcg_version = "3.5.0" %}
{% set zimpl_version = "3.5.1" %}
{% set bliss_version = "0.73.3" %}
# For dispatching between Unix and Windows
{% set install_prefix = "." %}        # [unix]
{% set install_prefix = "Library" %}  # [win]


package:
  name: scipoptsuite
  version: {{ scip_version }}

source:
  - url: https://scipopt.org/download/release/scipoptsuite-{{ scip_version }}.tgz
    sha256: 74c2bb3be6b9b99e75b03b3161ebcfbfb1d211e7becdd9929328a6e92ffce5a7
    folder: scipoptsuite
    patches:
      - 0001-Change-FindIPOPT.cmake.patch
  - url: https://github.com/ds4dm/Bliss/archive/v{{ bliss_version }}.tar.gz
    sha256: 4f51d9f76f7e8cb941688a032d208c79858f68a95f8eb69ebef64c62932c3eb7
    folder: bliss

build:
  number: 1

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make            # [unix]
  host:
    - tbb-devel
    - libblas
    - zlib
    - ipopt
    - cppad
    - boost-cpp 1.72  # [win]
    - boost-cpp       # [unix]
    - gmp             # [unix]
    - cliquer         # [unix]
    - bison           # [unix]
    - flex            # [unix]
    - gnuplot         # [not arm64]

outputs:

  - name: papilo
    version: {{ papilo_version }}
    requirements:
      build:
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - zlib
        - gmp             # [unix]
        - boost-cpp       # [unix]
        - boost-cpp 1.72  # [win]
        - libblas
      run:
        - tbb-devel
    files:
      - "{{ install_prefix }}/lib/cmake/papilo/"
      # Executable is not installed by Papilo's CMake
      # - "{{ install_prefix }}/bin/papilo*"
      # Vendored libraries
      - "{{ install_prefix }}/lib/libclusol*"
      - "{{ install_prefix }}/include/papilo/"
      - "{{ install_prefix }}/include/papilo-external/"

  - name: scip
    version: {{ scip_version }}
    build:
      run_exports:
        - {{ pin_subpackage('scip') }}
    requirements:
      build:
        - {{ compiler('c') }}
        # Soplex statically linked
        - {{ compiler('cxx') }}
        # Papilo statically linked but needs direct dependency from used shared libs.
        - {{ compiler('fortran') }}
      host:
        - zlib
        - ipopt
        - cppad
        - gmp  # [unix]
        # Papilo statically linked
        # Papilo statically linked but needs direct dependency from used shared libs.
        - tbb-devel
        - libblas
    files:
      - "{{ install_prefix }}/lib/libscip*"
      - "{{ install_prefix }}/lib/cmake/scip/"
      - "{{ install_prefix }}/bin/scip*"
      - "{{ install_prefix }}/bin/libscip*"  # [win]
      - "{{ install_prefix }}/include/blockmemshell/"
      - "{{ install_prefix }}/include/dijkstra/"
      - "{{ install_prefix }}/include/lpi/"
      - "{{ install_prefix }}/include/nlpi/"
      - "{{ install_prefix }}/include/objscip/"
      - "{{ install_prefix }}/include/scip/"
      - "{{ install_prefix }}/include/symmetry/"
      - "{{ install_prefix }}/include/tclique/"
      - "{{ install_prefix }}/include/tinycthread/"
      - "{{ install_prefix }}/include/tpi/"
      - "{{ install_prefix }}/include/xml/"

    test:
      script: run_scip_test.sh   # [unix]
      script: run_scip_test.bat  # [win]
      source_files:
        - scipoptsuite/scip/examples/Queens
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - make                   # [unix]

  - name: soplex
    version: {{ soplex_version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        # Papilo statically linked but needs direct dependency from used shared libs.
        - {{ compiler('fortran') }}
      host:
        - zlib
        - gmp             # [unix]
        - boost-cpp       # [unix]
        - boost-cpp 1.72  # [win]
        # Papilo statically linked but needs direct dependency from used shared libs.
        - tbb-devel
        - libblas
      run:
        # libboost_program_options.so needed by bin/soplex.
        # boost does not set run_exports so it is needed in run requirements.
        - boost-cpp
        - zlib
        - {{ pin_subpackage('papilo', exact=True) }}
    files:
      - "{{ install_prefix }}/lib/libsoplex*"
      - "{{ install_prefix }}/lib/cmake/soplex/"
      - "{{ install_prefix }}/bin/soplex*"
      - "{{ install_prefix }}/bin/libsoplex*"  # [win]
      - "{{ install_prefix }}/include/soplex*"
      - "{{ install_prefix }}/include/soplex/"
    test:
      script: run_soplex_test.sh   # [unix]
      script: run_soplex_test.bat  # [win]
      source_files:
        - scipoptsuite/soplex/src/example.cpp
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - make                     # [unix]
        # Papilo statically linked
        - {{ compiler('fortran') }}

  - name: gcg
    version:  {{ gcg_version }}
    build:
      skip: True  # [win]
      run_exports:
        - {{ pin_subpackage('gcg') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - gmp
        - cliquer
        - gnuplot  # [not arm64]
        - {{ pin_subpackage('scip', exact=True) }}
      run:
        - {{ pin_subpackage('scip') }}
        # run_exports not set for cliquer
        - cliquer
    files:
      - "lib/libgcg*"
      - "lib/cmake/gcg"
      - "bin/gcg"
      - "include/gcg"
    test:
      commands:
        - gcg --version
        - test -d "${PREFIX}/lib/cmake/gcg"
        - test -d "${PREFIX}/include/gcg"

  - name: zimpl
    version: {{ zimpl_version }}
    build:
      # zimpl is not built in Windows since gmp is not available on 
      # conda-forge so this test is skipped. Details were left for 
      # the path to zimpl if we find a solution in the future.  
      skip: True  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - zlib
        - gmp    # [unix]
        - bison  # [unix]
        - flex   # [unix]
    files:
      - "{{ install_prefix }}/lib/libzimpl*"
      - "{{ install_prefix }}/lib/cmake/zimpl/"
      - "{{ install_prefix }}/bin/zimpl*"
      - "{{ install_prefix }}/bin/libzimpl*"  # [win]
      - "{{ install_prefix }}/include/zimpl"
    test:
      commands:
        - zimpl -V
        - test -d "${PREFIX}/lib/cmake/zimpl"                                   # [unix]
        - test -d "${PREFIX}/include/zimpl"                                     # [unix]
        - if exist %PREFIX%\\Library\\lib\\cmake\\zimpl (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\\Library\\include\\zimpl (exit 0) else (exit 1)     # [win]


about:
  home: https://scipopt.org/
  license: ZIB-Academic AND LGPL-3.0-or-later
  license_file:
    - scipoptsuite/papilo/COPYING
    - scipoptsuite/papilo/external/lusol/LICENSE.md
    - scipoptsuite/papilo/external/pdqsort/license.txt
    - scipoptsuite/papilo/external/ska/LICENSE.txt
    - scipoptsuite/soplex/COPYING
    - scipoptsuite/scip/COPYING
    - scipoptsuite/gcg/LICENSE
    - scipoptsuite/zimpl/LICENSE
    - bliss/COPYING
    - bliss/include/bliss/utils.hh
  summary: Mixed Integer Programming (MIP) solver and Branch-and-Cut-and-Price Framework

extra:
  recipe-maintainers:
    - AntoinePrv
    - pokutta
    - fschloesser
