schema_version: 1

context:
  # TODO check these versions have not changed
  scip_version: 10.0.2
  papilo_version: 3.0.0
  soplex_version: 8.0.2
  gcg_version: 4.0.2
  zimpl_version: 3.7.1
  # to reduce disk space use on Windows, I disabled the Fortran compiler there
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=windows-images%2Cyaml#my-pipeline-fails-with-the-error-no-space-left-on-device
  # this disables LUSOL for Papilo, and then libblas is no longer needed as well
  papilo_with_lusol: ${{ unix }}

recipe:
  name: scipoptsuite
  version: ${{ scip_version }}

source:
  #url: https://scipopt.org/download/release/scipoptsuite-${{ scip_version }}.tgz
  url: https://github.com/scipopt/scip/releases/download/v${{ scip_version }}/scipoptsuite-${{ scip_version }}.tgz
  sha256: eecc29f31e8c8a3089c95ef99dd310d05e1546ba40f4ff36551d75a5f5c47073
  target_directory: scipoptsuite
  patches:
    - if: win
      then:
        # header-only does not work with current boost due to
        # https://github.com/boostorg/serialization/issues/232
        - 0001-disable-boost-no-lib.patch
        # conda-forge::jansson for windows contains only a static debug lib of jansson;
        # make gcg use this one
        - 0002-allow-jansson-debug-lib.patch

build:
  number: 1

outputs:

  # The papilo library built first
  - package:
      name: libpapilo-static
      version: ${{ papilo_version }}
    requirements:
      build:
        - ${{ compiler("fortran") if papilo_with_lusol }}
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - ${{ compiler("cxx") }}
        - cmake
        - ninja
      host:
        - tbb-devel
        - gmp
        - libboost-devel
        - ${{ "libblas" if papilo_with_lusol }}
      run:
        - ${{ pin_compatible("tbb-devel", exact=True) }}
      ignore_run_exports:
        from_package:
          # Required, but not used when building library
          - libboost-devel
    tests:
      - package_contents:
          # Explicitly no executable in this output
          strict: true
          lib:
            - libpapilo-core.${{ "a" if unix else "lib" }}
            - if: papilo_with_lusol
              then:
                - libclusol.${{ "a" if unix else "lib" }}
          include:
            - papilo/**/*
          files:
            - ${{ "Library/" if win }}lib/cmake/papilo/**/*
            - ${{ "Library/" if win }}share/licenses/papilo/**/*

  # The papilo executable will be built when scip is available
  - package:
      name: papilo
      version: ${{ papilo_version }}
    requirements:
      build:
        - ${{ compiler("fortran") if papilo_with_lusol }}
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - ${{ compiler("cxx") }}
        - cmake
        - ninja
      host:
        - tbb-devel
        - gmp
        - libboost-devel
        - highs
        - ${{ "libblas" if papilo_with_lusol }}
        - ${{ pin_subpackage("scip", exact=True) }}
      run:
        # Backward compatibility, `papilo` package will get all assets
        - ${{ pin_subpackage("libpapilo-static", exact=True) }}
      ignore_run_exports:
        from_package:
          # Required, but not used when building library
          - libboost-devel
    tests:
      - package_contents:
          strict: true
          bin:
            - papilo
      - script:
          - papilo --version

  - package:
      name: soplex
      version: ${{ soplex_version }}
    requirements:
      build:
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        # Papilo statically linked but may need Fortran compilier
        - ${{ compiler("fortran") if papilo_with_lusol }}
      host:
        - zlib
        - gmp
        - mpfr
        - libboost-devel
        - ${{ pin_subpackage("libpapilo-static", exact=True) }}
      run:
        - ${{ pin_subpackage("libpapilo-static", exact=True) }}
        - ${{ pin_compatible("libboost-devel", exact=True) }}
    tests:
      - package_contents:
          strict: true
          bin:
            - soplex
          lib:
            - libsoplexshared
            - libsoplex.${{ "a" if unix else "lib" }}
            - libsoplex-pic.${{ "a" if unix else "lib" }}
          include:
            - soplex/**/*
            - soplex*
          files:
            - ${{ "Library/" if win }}lib/cmake/soplex/**/*
            - ${{ "Library/" if win }}share/licenses/soplex/**/*
            - etc/conda/test-files/soplex/**/*
      - script:
          - soplex --version
      - script:
          file: run_soplex_test.nu
        files:
          source:
            - scipoptsuite/soplex/src/example.cpp
        requirements:
          build:
            - nushell
          run:
            - ${{ compiler("cxx") }}
            - cmake
            - ninja
            # Papilo statically linked but may need Fortran compilier
            - ${{ compiler("fortran") if papilo_with_lusol }}
            # Soplex static libs
            - zlib

  - package:
      name: zimpl
      version: ${{ zimpl_version }}
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - if: unix
          then:
            - bison
            - flex
          else:
            - winflexbison
      host:
        - zlib
        - gmp
        - ${{ "pcre2" if win }}
      run:
        - ${{ pin_compatible("pcre2", exact=True) if win }}
    tests:
      - package_contents:
          strict: true
          bin:
            - zimpl
          lib:
            - if: unix
              then:
                - libzimpl.a
                - libzimpl-pic.a
              else:
                - zimpl.lib
                - zimpl-pic.lib
          include:
            - zimpl/**/*
            - ${{ "WIN/*" if win }}
          files:
            - ${{ "Library/" if win }}lib/cmake/zimpl/**/*
            - ${{ "Library/" if win }}share/licenses/zimpl/**/*
      - script:
          - zimpl -V

  - package:
      name: scip
      version: ${{ scip_version }}
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        # Soplex statically linked needs C++ compiler
        - ${{ compiler("cxx") }}
        # Papilo statically linked but may need Fortran compilier
        - ${{ compiler("fortran") if papilo_with_lusol }}
      host:
        - zlib
        - ipopt
        - gmp
        - mpfr
        - ${{ pin_subpackage("libpapilo-static", exact=True) }}
        - ${{ pin_subpackage("soplex", exact=True) }}
        - ${{ pin_subpackage("zimpl", exact=True) }}
        # From transitive dependencies
        - tbb-devel
        - libboost-devel
        - ${{ "libblas" if papilo_with_lusol }}
        - ${{ "pcre2" if win }}
      run_exports:
        - ${{ pin_subpackage("scip") }}
    tests:
      - package_contents:
          strict: true
          bin:
            - scip
          lib:
            - libscip
          include:
            - scip/**/*
            - objscip/**/*
            - blockmemshell/**/*
            - dijkstra/**/*
            - lpi/**/*
            - lpiexact/**/*
            - rectlu/**/*
            - symmetry/**/*
            - tclique/**/*
            - tinycthread/**/*
            - tpi/**/*
            - xml/**/*
          files:
            - ${{ "Library/" if win }}lib/cmake/scip/**/*
            - ${{ "Library/" if win }}share/licenses/scip/**/*
            - etc/conda/test-files/scip/**/*
      - script:
          - scip --version
      - script:
          file: run_scip_test.nu
        files:
          source:
            - scipoptsuite/scip/examples/Queens
        requirements:
          build:
            - nushell
          run:
            - ${{ compiler("cxx") }}
            - cmake
            - ninja

  - package:
      name: gcg
      version: ${{ gcg_version }}
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - ${{ compiler("cxx") }}
        - cmake
        - ninja
      host:
        - gmp
        - ${{ "cliquer" if unix }}
        - ${{ "gnuplot" if unix }}
        - jansson
        - highs
        - ${{ "libgomp" if linux else "llvm-openmp" }}
        - ${{ pin_subpackage("scip", exact=True) }}
        # From transitive dependencies
        - ${{ pin_subpackage("libpapilo-static", exact=True) }}
        - tbb-devel
        - libboost-devel
      run:
        - ${{ pin_subpackage("scip") }}
        # run_exports not set for cliquer
        - ${{ pin_compatible("cliquer", exact=True) if unix }}
        - ${{ pin_compatible("highs", exact=True) }}
      run_exports:
        - ${{ pin_subpackage("gcg") }}
    tests:
      - package_contents:
          strict: true
          bin:
            - gcg
          lib:
            - libgcg
          include:
            - gcg/**/*
            - graph/**/*
          files:
            - ${{ "Library/" if win }}lib/cmake/gcg/**/*
            - ${{ "Library/" if win }}share/licenses/gcg/**/*
      - script:
          - gcg --version


about:
  license: Apache-2.0 AND LGPL-3.0-or-later AND EPL-1.0 and MIT and Zlib and BSL-1.0 and HPND
  license_file:
    - scipoptsuite/papilo/LICENSE  # Apache 2.0
    - scipoptsuite/papilo/src/papilo/external/lusol/LICENSE.md  # BSD or MIT
    - scipoptsuite/papilo/src/papilo/external/pdqsort/license.txt  # Zlib
    - scipoptsuite/papilo/src/papilo/external/ska/LICENSE.txt  # Boost 1.0 (BSL-1.0)
    - scipoptsuite/papilo/src/papilo/external/fmt/LICENSE.rst  # MIT
    - scipoptsuite/soplex/LICENSE  # Apache 2.0
    - scipoptsuite/soplex/src/soplex/external/zstr/License.txt  # MIT
    - scipoptsuite/soplex/src/soplex/external/fmt/LICENSE.rst  # MIT
    - scipoptsuite/scip/LICENSE  # Apache 2.0
    - scipoptsuite/scip/src/amplmp/LICENSE.rst  # HPND, similar to ISC
    - scipoptsuite/scip/src/cppad/COPYING  # EPL-1.0
    - scipoptsuite/scip/src/dejavu/LICENSE  # MIT
    - scipoptsuite/scip/src/nauty/COPYRIGHT  # Apache 2.0
    - scipoptsuite/scip/src/tclique/LICENSE  # Apache 2.0
    - scipoptsuite/scip/src/tinycthread/COPYRIGHT  # Zlib
    - scipoptsuite/gcg/LICENSE  # Apache 2.0
    - scipoptsuite/zimpl/LICENSE  # LGPL 3
  summary: Constraint Integer Programming and Branch-and-Cut-and-Price Framework
  homepage: https://scipopt.org/

extra:
  recipe-maintainers:
    - AntoinePrv
    - scip-ci
