build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
bot:
  automerge: true
conda_build:
  pkg_format: '2'
